server:
  port: 10000

spring:
  messages:
    basename: message/messages

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://{DB_HOST}:3306/bookstore?serverTimezone=Asia/Jakarta
    username: {DB_USERNAME}
    password: {DB_PASSWORD}